// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Vercel 构建跑 `prisma generate` 时也会加载本文件。
// 用 env("DATABASE_URL") 在变量未配置时会直接失败；
// generate 并不连库，因此允许占位；真正连库看运行时的 DATABASE_URL。
const datasourceUrl =
  process.env.DATABASE_URL ??
  process.env.POSTGRES_URL ??
  "postgresql://build:build@127.0.0.1:5432/build";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: datasourceUrl,
  },
});
